# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9eb476bbf582e2f00eb20bd1d37ca34b21ae679c677d5f8063c60b0b66c8c76bf23e5fb9da288702702acdfc21c2533a3f2177e92ea8463aa9d3d13308b0b06

test:
  secret_key_base: 276f7f643e0d05cf158f53cfc20cd1f60a8c5ee3959300f6018cfc5d10cc9bc04efd7caf7ddd0bf16e075d51b416e79b01cb7c5c834508880c197114fc754deb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
